name: Run project

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: run code
        run: |
          go run .

      - name: Commit cheats
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '848146+loganmc10@users.noreply.github.com'
          git add cheats.json
          git diff-index --quiet HEAD || git commit -am "Update cheats"
          git push
