name: Run project

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m --enable-all --disable wsl,gocritic,funlen,depguard,exhaustivestruct,varnamelen

      - name: run code
        run: |
          go run .
