name: Run project

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m --enable-all --disable wsl,gocritic,funlen,depguard,exhaustivestruct,varnamelen,nestif,cyclop,exhaustruct,revive

      - name: run code
        run: |
          go run .

      - name: Commit cheats
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '848146+loganmc10@users.noreply.github.com'
          git add cheats.json
          git commit -am "Update cheats"
          git push
